stages:
  - lint
  - test
  - build
  - e2e
  - publish

variables:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"

include:
  - local: .gitlab/ci/renovate.yml
  - local: .gitlab/ci/backend.yml
  - local: .gitlab/ci/frontend.yml
  - local: .gitlab/ci/e2e.yml
  - local: .gitlab/ci/publish.yml
